apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  volumes:
  - name: busybox-secret-volume
    secret:
      secretName: postgres-demo-0
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 600"] 
    volumeMounts:
    - name: busybox-secret-volume
      mountPath: /busybox-data