apiVersion: v1
kind: Pod
metadata:
  name: private-pod # name of the pod
spec:
  containers:
  - name: example-container
    image: mercy30/private-image # a private image in Docker Hub
    ports:
      - containerPort: 80
  imagePullSecrets:
  - name: auth-token